FORTRAN_COMPILER = gfortran

DELETE = rm -rf
MAKEDIR = mkdir -p
PRINT = echo

SOURCE_DIRECTORY = src
MODULE_DIRECTORY = mod
BINARY_DIRECTORY = bin
OBJECT_DIRECTORY = obj
OUTPUT_DIRECTORY = out

SOURCE_EXTENSION = .f90
MODULE_EXTENSION = .mod
BINARY_EXTENSION = .exe
OUTPUT_EXTENSION = .plt
OBJECT_EXTENSION = .o

SOURCE_FILES = $(wildcard $(SOURCE_DIRECTORY)/*$(SOURCE_EXTENSION))

OBJECT_FILES = $(patsubst $(SOURCE_DIRECTORY)/%$(SOURCE_EXTENSION), \
	$(OBJECT_DIRECTORY)/%$(OBJECT_EXTENSION), $(SOURCE_FILES))

MODULE_FILES = $(patsubst $(OBJECT_DIRECTORY)/%$(OBJECT_EXTENSION), \
	$(MODULE_DIRECTORY)/%$(MODULE_EXTENSION), $(OBJECT_FILES))

OUTPUT_FILES = $(wildcard $(OUTPUT_DIRECTORY)/*$(OUTPUT_EXTENSION))

SOURCE_FILE = $(wildcard *$(SOURCE_EXTENSION))

EXECUTABLE = $(patsubst %$(SOURCE_EXTENSION), \
	$(BINARY_DIRECTORY)/%$(BINARY_EXTENSION), $(SOURCE_FILE))

start: setup $(EXECUTABLE)
	@$(EXECUTABLE)

$(EXECUTABLE): $(OBJECT_FILES) $(SOURCE_FILE)
	$(FORTRAN_COMPILER) -J $(MODULE_DIRECTORY) -o $@ $^

$(OBJECT_DIRECTORY)/%$(OBJECT_EXTENSION): $(SOURCE_DIRECTORY)/%$(SOURCE_EXTENSION)
	$(FORTRAN_COMPILER) -J $(MODULE_DIRECTORY) -o $@ -c $<

setup:
	@$(MAKEDIR) $(BINARY_DIRECTORY) $(MODULE_DIRECTORY) $(OBJECT_DIRECTORY) \
		$(OUTPUT_DIRECTORY)

clean:
	@$(DELETE) $(OBJECT_FILES) $(MODULE_FILES) $(EXECUTABLE)

debug:
	@$(PRINT) "SOURCE FILES:" $(SOURCE_FILES)
	@$(PRINT) "OBJECT FILES:" $(OBJECT_FILES)
	@$(PRINT) "MODULE FILES:" $(MODULE_FILES)
	@$(PRINT) "OUTPUT FILES:" $(OUTPUT_FILES)

.PHONY: start setup clean debug
